2021-05-10 15:37:50,145 - D:/pyworkspace/autodemo/log/my_log.py[line:51] - ERROR: error
2021-05-10 16:26:55,634 - D:/pyworkspace/autodemo/log/my_log.py[line:52] - ERROR: error
